module Checkers.FrontEnd.Types where

import Checkers.Types


{-
  A player is either an AI or a human, where an AI has its move generated by a GenMove,
  whereas the frontend must get information from the user for a human move.
-}
data PlayerType = Ai GenMove | Human

{-
  The GameConfig type is the configuration for a checkers game.
  This includes the engine, the two players, and the state of the game.
-}
data GameConfig = 
  GameConfig { engine :: CheckersEngine
             , blackMove :: PlayerType
             , redMove :: PlayerType
             , state :: GameState}

{-
  A frontend takes in a game configuration and returns an IO (), 
  which is the game loop.
-}
type FrontEnd = GameConfig -> IO ()
